from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet

# Create a router instance for Posts
router = DefaultRouter()

# Register the PostViewSet. Creates: /posts/, /posts/{pk}/, /posts/{pk}/like/
router.register(r'posts', PostViewSet, basename='post')

# We define the Comment URLs manually to nest them under a specific post.
# Note: The viewset uses self.kwargs['post_pk'] to filter
comment_list_routes = [
    # List all comments for a specific post and create new comments
    path(
        '<int:post_pk>/comments/', 
        CommentViewSet.as_view({'get': 'list', 'post': 'create'}), 
        name='post-comment-list'
    ),
    # Retrieve, update, and destroy a specific comment
    path(
        'comments/<int:pk>/', 
        CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), 
        name='comment-detail'
    ),
]

# The Post URLs (from the router) and the Comment URLs are combined.
urlpatterns = [
    # Include all post routes generated by the router
    path('', include(router.urls)),
    
    # Include the manually defined comment routes, which are nested under /posts/
    path('posts/', include(comment_list_routes)),
]
