from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentViewSet, UserFeedView 

# Create a router instance for Posts
router = DefaultRouter()

# Register the PostViewSet. Creates: /posts/, /posts/{pk}/, /posts/{pk}/like/
router.register(r'posts', PostViewSet, basename='post')

# Manual URL configuration for comments (nested under posts)
comment_routes = [
    # List all comments for a specific post and create new comments
    path(
        '<int:post_pk>/comments/', 
        CommentViewSet.as_view({'get': 'list', 'post': 'create'}), 
        name='post-comment-list'
    ),
    # Retrieve, update, and destroy a specific comment
    path(
        'comments/<int:pk>/', 
        CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), 
        name='comment-detail'
    ),
]

# The complete list of URL patterns
urlpatterns = [
    # New Feed Endpoint (Task 2) - This includes the required "feed/" string
    path('feed/', UserFeedView.as_view(), name='user-feed'),
    
    # Include all post routes generated by the router
    path('', include(router.urls)),
    
    # Include the manually defined comment routes, which are nested under /posts/
    path('posts/', include(comment_routes)),
]
